### ISSUE TITLE
an error in "Point_cloud_data_sub_sampling_with_Python"

### ISSUE THREAD

**Issue by whuwuteng** [florentPoux/point-cloud-processing#2]
Hello, I am not sure you maintain the code now or not, but in the function def grid_subsampling(points, voxel_size), there is no reference for subsampled_points, I think the code is not runnable.
Thank you.

**Comment by florentPoux** [comment]
@whuwuteng thank you for noticing! I updated the Notebook to function properly! Have fun,

Florent
